### PR TITLE
RETURN returning wrong amount of values

### PR DESCRIPTION
**Pull request by SnowyShiro**
RETURN is returning the wrong amount of values. RETURN seems to be returning the correct number + the proto param count.

### CODE REVIEW

**Comment by TheGreatSageEqualToHeaven** [comment]
Must've missed this, could you add a test to check for this in the future?

**Comment by TheGreatSageEqualToHeaven** [comment]
On the topic of tests I should probably add some automatic ci to test, I haven't had time to properly port Luau's conformance tests so a few bugs have been missed. Once Luau's conformance tests pass when they're implemented I'll make a proper release for Fiu.

**Comment by SnowyShiro** [comment]
> Must've missed this, could you add a test to check for this in the future?

How would I do that? The values it tries to return are usually nil, since it goes past the stack.

**Comment by TheGreatSageEqualToHeaven** [comment]
> How would I do that? The values it tries to return are usually nil, since it goes past the stack.

Make a file called "Returns" in Sources and run `CreateTests`

**Comment by TheGreatSageEqualToHeaven** [comment]
I've added the conformance tests and split up my original tests into staging. I'll take a look at making conformance tests work properly next month hopefully. I have also added tests for your fix under a staging test called "Returns". Once all tests pass I'll make a proper release for Fiu and then implement github actions for testing Fiu every time Luau updates and for pull requests. Thank you for the fix.

**Pull request merged**
